// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.dkohut.bookchat.server.common.entity;

/**
 * Protobuf enum {@code com.dkohut.bookchat.server.common.entity.AccessEnum}
 */
public enum AccessEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ACCESS_GRANTED = 0;</code>
   */
  ACCESS_GRANTED(0),
  /**
   * <code>ACCESS_DENIED = 1;</code>
   */
  ACCESS_DENIED(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ACCESS_GRANTED = 0;</code>
   */
  public static final int ACCESS_GRANTED_VALUE = 0;
  /**
   * <code>ACCESS_DENIED = 1;</code>
   */
  public static final int ACCESS_DENIED_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AccessEnum valueOf(int value) {
    return forNumber(value);
  }

  public static AccessEnum forNumber(int value) {
    switch (value) {
      case 0: return ACCESS_GRANTED;
      case 1: return ACCESS_DENIED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AccessEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AccessEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AccessEnum>() {
          public AccessEnum findValueByNumber(int number) {
            return AccessEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.dkohut.bookchat.server.common.entity.UserServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final AccessEnum[] VALUES = values();

  public static AccessEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AccessEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.dkohut.bookchat.server.common.entity.AccessEnum)
}

