// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.dkohut.bookchat.server.common.entity;

public final class UserServiceOuterClass {
  private UserServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_server_common_entity_AccessInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_server_common_entity_AccessInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_server_common_entity_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_server_common_entity_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_server_common_entity_LoginMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_server_common_entity_LoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022(com.dkohut.bookchat" +
      ".server.common.entity\032\021BookService.proto" +
      "\"R\n\nAccessInfo\022D\n\006access\030\001 \001(\01624.com.dko" +
      "hut.bookchat.server.common.entity.Access" +
      "Enum\"P\n\004User\022\n\n\002id\030\001 \001(\005\022\r\n\005login\030\002 \001(\t\022" +
      "\020\n\010password\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\r\n\005email" +
      "\030\005 \001(\t\"/\n\014LoginMessage\022\r\n\005login\030\001 \001(\t\022\020\n" +
      "\010password\030\002 \001(\t*3\n\nAccessEnum\022\022\n\016ACCESS_" +
      "GRANTED\020\000\022\021\n\rACCESS_DENIED\020\0012\377\001\n\013UserSer" +
      "vice\022y\n\014registration\022..com.dkohut.bookch",
      "at.server.common.entity.User\0329.com.dkohu" +
      "t.bookchat.server.common.entity.Response" +
      "Message\022u\n\005login\0226.com.dkohut.bookchat.s" +
      "erver.common.entity.LoginMessage\0324.com.d" +
      "kohut.bookchat.server.common.entity.Acce" +
      "ssInfoB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dkohut.bookchat.server.common.entity.BookServiceOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_dkohut_bookchat_server_common_entity_AccessInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dkohut_bookchat_server_common_entity_AccessInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_server_common_entity_AccessInfo_descriptor,
        new java.lang.String[] { "Access", });
    internal_static_com_dkohut_bookchat_server_common_entity_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dkohut_bookchat_server_common_entity_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_server_common_entity_User_descriptor,
        new java.lang.String[] { "Id", "Login", "Password", "Name", "Email", });
    internal_static_com_dkohut_bookchat_server_common_entity_LoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_dkohut_bookchat_server_common_entity_LoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_server_common_entity_LoginMessage_descriptor,
        new java.lang.String[] { "Login", "Password", });
    com.dkohut.bookchat.server.common.entity.BookServiceOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
