// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.dkohut.bookchat.common.entity;

/**
 * <pre>
 * Message sent to client with info about access to system
 * </pre>
 *
 * Protobuf type {@code com.dkohut.bookchat.common.entity.AccessInfo}
 */
public  final class AccessInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.dkohut.bookchat.common.entity.AccessInfo)
    AccessInfoOrBuilder {
  // Use AccessInfo.newBuilder() to construct.
  private AccessInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AccessInfo() {
    access_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AccessInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            access_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.dkohut.bookchat.common.entity.UserServiceOuterClass.internal_static_com_dkohut_bookchat_common_entity_AccessInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.dkohut.bookchat.common.entity.UserServiceOuterClass.internal_static_com_dkohut_bookchat_common_entity_AccessInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.dkohut.bookchat.common.entity.AccessInfo.class, com.dkohut.bookchat.common.entity.AccessInfo.Builder.class);
  }

  public static final int ACCESS_FIELD_NUMBER = 1;
  private int access_;
  /**
   * <code>.com.dkohut.bookchat.common.entity.AccessEnum access = 1;</code>
   */
  public int getAccessValue() {
    return access_;
  }
  /**
   * <code>.com.dkohut.bookchat.common.entity.AccessEnum access = 1;</code>
   */
  public com.dkohut.bookchat.common.entity.AccessEnum getAccess() {
    com.dkohut.bookchat.common.entity.AccessEnum result = com.dkohut.bookchat.common.entity.AccessEnum.valueOf(access_);
    return result == null ? com.dkohut.bookchat.common.entity.AccessEnum.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (access_ != com.dkohut.bookchat.common.entity.AccessEnum.ACCESS_GRANTED.getNumber()) {
      output.writeEnum(1, access_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (access_ != com.dkohut.bookchat.common.entity.AccessEnum.ACCESS_GRANTED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, access_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.dkohut.bookchat.common.entity.AccessInfo)) {
      return super.equals(obj);
    }
    com.dkohut.bookchat.common.entity.AccessInfo other = (com.dkohut.bookchat.common.entity.AccessInfo) obj;

    boolean result = true;
    result = result && access_ == other.access_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCESS_FIELD_NUMBER;
    hash = (53 * hash) + access_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.dkohut.bookchat.common.entity.AccessInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.dkohut.bookchat.common.entity.AccessInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message sent to client with info about access to system
   * </pre>
   *
   * Protobuf type {@code com.dkohut.bookchat.common.entity.AccessInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.dkohut.bookchat.common.entity.AccessInfo)
      com.dkohut.bookchat.common.entity.AccessInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dkohut.bookchat.common.entity.UserServiceOuterClass.internal_static_com_dkohut_bookchat_common_entity_AccessInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dkohut.bookchat.common.entity.UserServiceOuterClass.internal_static_com_dkohut_bookchat_common_entity_AccessInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dkohut.bookchat.common.entity.AccessInfo.class, com.dkohut.bookchat.common.entity.AccessInfo.Builder.class);
    }

    // Construct using com.dkohut.bookchat.common.entity.AccessInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      access_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.dkohut.bookchat.common.entity.UserServiceOuterClass.internal_static_com_dkohut_bookchat_common_entity_AccessInfo_descriptor;
    }

    public com.dkohut.bookchat.common.entity.AccessInfo getDefaultInstanceForType() {
      return com.dkohut.bookchat.common.entity.AccessInfo.getDefaultInstance();
    }

    public com.dkohut.bookchat.common.entity.AccessInfo build() {
      com.dkohut.bookchat.common.entity.AccessInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.dkohut.bookchat.common.entity.AccessInfo buildPartial() {
      com.dkohut.bookchat.common.entity.AccessInfo result = new com.dkohut.bookchat.common.entity.AccessInfo(this);
      result.access_ = access_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.dkohut.bookchat.common.entity.AccessInfo) {
        return mergeFrom((com.dkohut.bookchat.common.entity.AccessInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.dkohut.bookchat.common.entity.AccessInfo other) {
      if (other == com.dkohut.bookchat.common.entity.AccessInfo.getDefaultInstance()) return this;
      if (other.access_ != 0) {
        setAccessValue(other.getAccessValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.dkohut.bookchat.common.entity.AccessInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.dkohut.bookchat.common.entity.AccessInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int access_ = 0;
    /**
     * <code>.com.dkohut.bookchat.common.entity.AccessEnum access = 1;</code>
     */
    public int getAccessValue() {
      return access_;
    }
    /**
     * <code>.com.dkohut.bookchat.common.entity.AccessEnum access = 1;</code>
     */
    public Builder setAccessValue(int value) {
      access_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.dkohut.bookchat.common.entity.AccessEnum access = 1;</code>
     */
    public com.dkohut.bookchat.common.entity.AccessEnum getAccess() {
      com.dkohut.bookchat.common.entity.AccessEnum result = com.dkohut.bookchat.common.entity.AccessEnum.valueOf(access_);
      return result == null ? com.dkohut.bookchat.common.entity.AccessEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.dkohut.bookchat.common.entity.AccessEnum access = 1;</code>
     */
    public Builder setAccess(com.dkohut.bookchat.common.entity.AccessEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      access_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.dkohut.bookchat.common.entity.AccessEnum access = 1;</code>
     */
    public Builder clearAccess() {
      
      access_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.dkohut.bookchat.common.entity.AccessInfo)
  }

  // @@protoc_insertion_point(class_scope:com.dkohut.bookchat.common.entity.AccessInfo)
  private static final com.dkohut.bookchat.common.entity.AccessInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.dkohut.bookchat.common.entity.AccessInfo();
  }

  public static com.dkohut.bookchat.common.entity.AccessInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccessInfo>
      PARSER = new com.google.protobuf.AbstractParser<AccessInfo>() {
    public AccessInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AccessInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AccessInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccessInfo> getParserForType() {
    return PARSER;
  }

  public com.dkohut.bookchat.common.entity.AccessInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

