// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.dkohut.bookchat.common.entity;

public final class BookServiceOuterClass {
  private BookServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_Book_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_SearchBookMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_SearchBookMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_DeleteBookMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_DeleteBookMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021BookService.proto\022!com.dkohut.bookchat" +
      ".common.entity\"i\n\004Book\022\n\n\002id\030\001 \001(\005\022\r\n\005ti" +
      "tle\030\002 \001(\t\022\r\n\005genre\030\003 \001(\t\022\016\n\006author\030\004 \001(\t" +
      "\022\030\n\020publication_date\030\005 \001(\t\022\r\n\005price\030\006 \001(" +
      "\002\"T\n\017ResponseMessage\022A\n\010response\030\001 \001(\0162/" +
      ".com.dkohut.bookchat.common.entity.Respo" +
      "nseEnum\"\"\n\021SearchBookMessage\022\r\n\005title\030\001 " +
      "\001(\t\"\037\n\021DeleteBookMessage\022\n\n\002id\030\001 \001(\005*&\n\014" +
      "ResponseEnum\022\013\n\007SUCCESS\020\000\022\t\n\005ERROR\020\0012\335\002\n" +
      "\013BookService\022i\n\ncreateBook\022\'.com.dkohut.",
      "bookchat.common.entity.Book\0322.com.dkohut" +
      ".bookchat.common.entity.ResponseMessage\022" +
      "k\n\nsearchBook\0224.com.dkohut.bookchat.comm" +
      "on.entity.SearchBookMessage\032\'.com.dkohut" +
      ".bookchat.common.entity.Book\022v\n\ndeleteBo" +
      "ok\0224.com.dkohut.bookchat.common.entity.D" +
      "eleteBookMessage\0322.com.dkohut.bookchat.c" +
      "ommon.entity.ResponseMessageB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_dkohut_bookchat_common_entity_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dkohut_bookchat_common_entity_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_Book_descriptor,
        new java.lang.String[] { "Id", "Title", "Genre", "Author", "PublicationDate", "Price", });
    internal_static_com_dkohut_bookchat_common_entity_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dkohut_bookchat_common_entity_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_ResponseMessage_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_com_dkohut_bookchat_common_entity_SearchBookMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_dkohut_bookchat_common_entity_SearchBookMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_SearchBookMessage_descriptor,
        new java.lang.String[] { "Title", });
    internal_static_com_dkohut_bookchat_common_entity_DeleteBookMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_dkohut_bookchat_common_entity_DeleteBookMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_DeleteBookMessage_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
