// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.dkohut.bookchat.common.entity;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dkohut.bookchat.common.entity.Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string genre = 3;</code>
   */
  java.lang.String getGenre();
  /**
   * <code>string genre = 3;</code>
   */
  com.google.protobuf.ByteString
      getGenreBytes();

  /**
   * <code>string author = 4;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 4;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string publication_date = 5;</code>
   */
  java.lang.String getPublicationDate();
  /**
   * <code>string publication_date = 5;</code>
   */
  com.google.protobuf.ByteString
      getPublicationDateBytes();

  /**
   * <code>float price = 6;</code>
   */
  float getPrice();
}
