// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatService.proto

package com.dkohut.bookchat.common.entity;

public final class ChatServiceOuterClass {
  private ChatServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dkohut_bookchat_common_entity_ChatMessageFromServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dkohut_bookchat_common_entity_ChatMessageFromServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatService.proto\022!com.dkohut.bookchat" +
      ".common.entity\",\n\013ChatMessage\022\014\n\004name\030\001 " +
      "\001(\t\022\017\n\007message\030\002 \001(\t\"6\n\025ChatMessageFromS" +
      "erver\022\014\n\004name\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2\201\001\n" +
      "\013ChatService\022r\n\004chat\022..com.dkohut.bookch" +
      "at.common.entity.ChatMessage\0328.com.dkohu" +
      "t.bookchat.common.entity.ChatMessageFrom" +
      "Server(\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_dkohut_bookchat_common_entity_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dkohut_bookchat_common_entity_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_ChatMessage_descriptor,
        new java.lang.String[] { "Name", "Message", });
    internal_static_com_dkohut_bookchat_common_entity_ChatMessageFromServer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dkohut_bookchat_common_entity_ChatMessageFromServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dkohut_bookchat_common_entity_ChatMessageFromServer_descriptor,
        new java.lang.String[] { "Name", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
