// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatService.proto

package com.dkohut.bookchat.common.entity;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dkohut.bookchat.common.entity.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
