// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.dkohut.bookchat.common.entity;

public interface LoginMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dkohut.bookchat.common.entity.LoginMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string login = 1;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>string login = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
