// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.dkohut.bookchat.common.entity;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dkohut.bookchat.common.entity.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.dkohut.bookchat.common.entity.ResponseEnum response = 1;</code>
   */
  int getResponseValue();
  /**
   * <code>.com.dkohut.bookchat.common.entity.ResponseEnum response = 1;</code>
   */
  com.dkohut.bookchat.common.entity.ResponseEnum getResponse();
}
