// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BookService.proto

package com.dkohut.bookchat.common.entity;

public interface SearchBookMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dkohut.bookchat.common.entity.SearchBookMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();
}
